# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Security Scorecard Test"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/security-scorecard-test.yml"
      - ".github/workflows/security-scorecard-reusable.yml"
  merge_group:
    types:
      - "checks_requested"
  workflow_dispatch:

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  security-scorecard-test:
    name: "Security Scorecard Test"
    permissions:
      actions: "read" # https://github.com/github/codeql-action/issues/2117
      security-events: "write" # Needed to to upload SARIF file to tab
      id-token: "write" # Needed for GitHub OIDC token if publish_results
      contents: "read"
    # enq: hash with name and version always longer than 80 chars
    # yamllint disable rule:line-length
    # enq: unpinned as it allows projects to use the latest
    uses: "open-nudge/opentemplate/.github/workflows/security-scorecard-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
...
