# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Security Semgrep Update"

on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  security-semgrep-update:
    permissions:
      actions: "read" # https://github.com/github/codeql-action/issues/2117
      security-events: "write" # Needed to to upload SARIF file to tab
      contents: "read"
    name: "Security Semgrep Update"
    # enq: hash with name and version always longer than 80 chars
    # yamllint disable rule:line-length
    # enq: unpinned as it allows projects to use the latest
    uses: "open-nudge/opentemplate/.github/workflows/security-semgrep-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      sarif: true
...
