# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Shell Reusable"

on:
  workflow_call:

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  shell-reusable:
    name: "Shell Reusable"
    permissions:
      contents: "read"
    # enq: hash with name and version always longer than 80 chars
    # yamllint disable rule:line-length
    # enq: unpinned as it allows projects to use the latest
    uses: "open-nudge/opentemplate/.github/workflows/run-check-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      check: "shell"
      sparse-checkout: |
        **.sh
      arguments: >
        $(find . -name '*.sh' ! -path './.venv/*')
...
