# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Stale"
on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_call:
  workflow_dispatch:

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  stale:
    timeout-minutes: 10
    name: "Stale"
    permissions:
      issues: "write" # Needed to close stale issues
      pull-requests: "write" # Needed to close stale pull requests
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76" # v2.14.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: "Mark stale PRs"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        uses: "actions/stale@5bef64f19d7facfb25b37b414482c7164d639639" # v9.1.0
        # yamllint enable rule:line-length
        with:
          stale-pr-message: >
            This pull request did not receive any commits in the last 7 days.
            Marking pull request as stale (push additional commits or
            merge to unstale it).
          close-pr-message: >
            This PR was stale for the last 7 days.
            Closing the PR (one can reopen it at any time
            by committing and/or merging).
          days-before-pr-stale: 14
          days-before-pr-close: 28
          stale-pr-label: "stale"
          close-pr-label: "expired"
          remove-pr-stale-when-updated: true
          labels-to-remove-when-unstale: "stale"
...
