# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Text Reusable"

on:
  workflow_call:

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  text-reusable:
    name: "Text Reusable"
    permissions:
      contents: "read"
    # enq: hash with name and version always longer than 80 chars
    # yamllint disable rule:line-length
    # enq: unpinned as it allows projects to use the latest
    uses: "open-nudge/opentemplate/.github/workflows/run-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      # Workaround for __pypackages__/README.md
      # It is collected automatically by pre-commit-hooks
      command: >
        rm -rf .git &&
        git init --initial-branch main &&
        pdm run check-text
      group: "text"
      full-checkout: true
...
