# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Text"

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "DCO.md"
      - "docs/DCO.md"
      - "LICENSE.md"
      - "docs/LICENSE.md"
      - "LICENSES/*"
  merge_group:
    types:
      - "checks_requested"

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  text:
    name: "Text"
    permissions:
      contents: "read"
    # enq: hash with name and version always longer than 80 chars
    # yamllint disable rule:line-length
    # enq: unpinned as it allows projects to use the latest
    uses: "open-nudge/opentemplate/.github/workflows/text-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
...
